#!/bin/bash
echo 'Verify the MAC and product_uuid address https://kubernetes.io/docs/setup/production-environm;ent/tools/kubeadm/install-kubeadm/#verify-mac-address';
ip link;
cat /sys/class/dmi/id/product_uuidecho;
echo 'https://kubernetes.io/docs/setup/production-environment/container-runtimes/#prerequisite-ipv4-forwarding-optional';
echo 'sysctl params required by setup, params persist across reboots';
cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.ipv4.ip_forward = 1
EOF
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
br_netfilter
overlay
EOF

echo 'Apply sysctl params without reboot';
sudo sysctl --system;
sysctl net.ipv4.ip_forward;

echo 'Installing kubeadm, kubelet and kubectl https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl';
apt-get update && apt-get install -y apt-transport-https ca-certificates curl gpg;
mkdir -p -m 755 /etc/apt/keyrings;
curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key  | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg;

echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list;
apt-get update;
apt-get install -y kubelet kubeadm kubectl;
apt-mark hold kubelet kubeadm kubectl;
systemctl enable --now kubelet;



